version: '2'

services:
  app:
    build:
      context: .
      args:
      - REQUIREMENTS_FILE=/requirements/dev.txt
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/appdb
      - DEBUG=True
    volumes:
    - ./src:/app
    depends_on:
    - db
    - mail
    ports:
    - "80:80"
    command: /start-reload.sh

  db:
    image: postgres
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=appdb
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./postgresql.conf:/etc/postgresql/postgresql.conf
    - ./.postgres:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  mail:
    image: mailhog/mailhog
    expose:
    - "1025"
    ports:
    - "8025:8025"
