version: '2'

services:
  app:
    build:
      context: .
      args:
      - REQUIREMENTS_FILE=/requirements/dev.txt
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/appdb
      - DEBUG=True
    volumes:
    - ./src:/app
    depends_on:
    - db
    - redis
    - mail
    ports:
    - "80:80"
    - "81:81"
    command: ["supervisord", "-n", "-c", "/supervisord.dev.conf"]
  db:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=appdb
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./.postgres:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
  redis:
    image: redis
  mail:
    image: mailhog/mailhog
    expose:
    - "1025"
    ports:
    - "8025:8025"
