version: '2'

services:
  app:
    build:
      context: .
      args:
      - REQUIREMENTS_FILE=/requirements/dev.txt
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/appdb
      - DEBUG=True
    volumes:
    - ./src:/app
    depends_on:
    - db
    ports:
    - "80:80"
    command: ['/start-reload.sh']
  db:
    image: postgres:9.6
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=appdb
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - ./.postgres:/var/lib/postgresql/data/pgdata
    ports:
    - "5432:5432"
