version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: python:3.7-alpine
        environment:
          ALLOWED_HOSTS: "*"
          DATABASE_URL: "postgresql://postgres:password@127.0.0.1:5432/appdb"
          SECRET_KEY: 'some-secret-key'
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: appdb
    steps:
      - checkout
      - run:
          command: |
            apk update && apk add \
            jpeg-dev \
            libmagic \
            libpq \
            make \
            postgresql-client \
            supervisor \
            zlib-dev \
            gcc \
            git \
            libc-dev \
            linux-headers \
            musl-dev \
            postgresql-dev
      - restore_cache:
          key: deps-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
      - run:
          command: |
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "/usr/local/bin"
            - "/usr/local/lib/python3.7/site-packages"
            - "/usr/local/share"
      - run:
          command: |
            cd src && ./scripts/test
